---
abstract: 'Markdown converter for HTML slide tools'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Markdown-Slidy
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Text::Markdown::Slidy:
    file: lib/Text/Markdown/Slidy.pm
    version: 0.02
requires:
  Text::Markdown: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-Text-Markdown-Slidy/issues
  homepage: https://github.com/Songmu/p5-Text-Markdown-Slidy
  repository: git://github.com/Songmu/p5-Text-Markdown-Slidy.git
version: 0.02
